
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Mar 19 2026 18:58:54 +06 (Mar 19 2026 12:58:54 UTC)

// Verification Directory fv/counter 

module add_unsigned(A, B, Z);
  input [7:0] A;
  input B;
  output [7:0] Z;
  wire [7:0] A;
  wire B;
  wire [7:0] Z;
  wire n_18, n_22, n_25, n_27, n_31, n_33, n_37, n_39;
  wire n_43, n_44, n_46, n_47, n_49, n_53, n_60, n_62;
  wire n_63, n_64, n_65, n_67, n_72, n_77, n_83, n_86;
  wire n_90;
  xor g1 (Z[0], A[0], B);
  nand g2 (n_18, A[0], B);
  nand g21 (n_25, n_22, A[1]);
  nor g26 (n_47, n_31, n_27);
  nor g30 (n_53, n_37, n_33);
  nand g36 (n_46, n_44, A[2]);
  nand g38 (n_49, n_47, n_44);
  nand g44 (n_64, n_53, A[6]);
  nand g51 (n_62, n_60, A[4]);
  nand g53 (n_63, n_53, n_60);
  not g55 (n_65, n_64);
  nand g56 (n_67, n_60, n_65);
  xnor g62 (Z[1], n_22, n_72);
  xnor g64 (Z[2], n_44, n_31);
  xnor g67 (Z[3], n_77, n_27);
  xnor g69 (Z[4], n_60, n_37);
  xnor g72 (Z[5], n_83, n_33);
  xnor g74 (Z[6], n_86, n_43);
  xnor g77 (Z[7], n_90, n_39);
  not g80 (n_31, A[2]);
  not g81 (n_27, A[3]);
  not g82 (n_37, A[4]);
  not g83 (n_33, A[5]);
  not g84 (n_43, A[6]);
  not g85 (n_39, A[7]);
  not g86 (n_22, n_18);
  not g87 (n_72, A[1]);
  not g88 (n_44, n_25);
  not g89 (n_77, n_46);
  not g90 (n_60, n_49);
  not g91 (n_83, n_62);
  not g92 (n_86, n_63);
  not g93 (n_90, n_67);
endmodule

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18;
  add_unsigned add_9_12(.A (count), .B (1'b1), .Z ({n_18, n_17, n_16,
       n_15, n_14, n_13, n_12, n_11}));
  not g1 (n_10, rst);
  CDN_flop \count_reg[0] (.clk (clk), .d (n_11), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[0]));
  CDN_flop \count_reg[1] (.clk (clk), .d (n_12), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[1]));
  CDN_flop \count_reg[2] (.clk (clk), .d (n_13), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[2]));
  CDN_flop \count_reg[3] (.clk (clk), .d (n_14), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[3]));
  CDN_flop \count_reg[4] (.clk (clk), .d (n_15), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[4]));
  CDN_flop \count_reg[5] (.clk (clk), .d (n_16), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[5]));
  CDN_flop \count_reg[6] (.clk (clk), .d (n_17), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[6]));
  CDN_flop \count_reg[7] (.clk (clk), .d (n_18), .sena (1'b1), .aclr
       (n_10), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (count[7]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
